name: CI pull request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'filedata/**'
      - 'ops/**'

jobs:
  build:
    uses: iganets/.github/.github/workflows/cmake-multi-platform.yml@main
    with:
      IGANET_OPTIONAL: "unittests"
    secrets: inherit
