name: CI pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    uses: iganets/.github/.github/workflows/cmake-multi-platform.yml@main
    with:
      cmake_flags: "-DIGANET_OPTIONAL=examples"
    secrets: inherit
