name: CI push

on:
  push:
    paths:
      - '.github/workflows/ci-push.yml'
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'filedata/**'
      - 'ops/**'

jobs:
  build:
    uses: iganets/.github/.github/workflows/cmake-multi-platform.yml@main
    with:
      IGANET_OPTIONAL: "examples"
    secrets: inherit
