name: Deploy to GitHub Pages

on:
  push:
  pull_request:
#    branches: [master]
  workflow_dispatch:  # Allows manual triggers of this workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: iganets/.github/.github/workflows/gh-pages.yml@main
    with:
      IGANET_OPTIONAL: "examples"
    secrets: inherit
