name: Deploy to GitHub Pages

on:
  push:
    paths:
      - '.github/workflows/gh-pages.yml'
    paths-ignore:
      - '.github/**'
      - 'cmake/**'
      - 'filedata/**'
      - 'ops/**'
  pull_request:
    paths:
      - '.github/workflows/gh-pages.yml'
    paths-ignore:
      - '.github/**'
      - 'cmake/**'
      - 'filedata/**'
      - 'ops/**'
#    branches: [master]
  workflow_dispatch:  # Allows manual triggers of this workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: iganets/.github/.github/workflows/gh-pages.yml@main
    with:
      IGANET_OPTIONAL: "examples;unittests;perftests"
    secrets: inherit
